import logoImg from '../../public/images/alkitabLogo.png';

export default function Head() {
  return (
    <>
      <title>Taleb Alelm</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link
        rel='icon'
        href={
          'https://cdn-icons-png.flaticon.com/512/29/29302.png?w=996&t=st=1687274127~exp=1687274727~hmac=840676480a457a765d0890fbbbfa180ba26c2185fa74580584f5afcb03d41ca1'
        }
      />
    </>
  );
}
